networks:
  ticketbooknetwork:

volumes:
  sql_data:  

services:
  azurite:
   container_name: azurite
   image : mcr.microsoft.com/azure-storage/azurite:latest
   restart: always
   ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002
   networks:
    - ticketbooknetwork

  ticketdb:
   container_name: ticket-db
   image: mcr.microsoft.com/mssql/server:2022-latest
   ports:
   - 1433:1433
   environment:
   - ACCEPT_EULA=Y
   - MSSQL_SA_PASSWORD=password@12345#
   volumes:
   - sql_data:/var/opt/mssql
   networks:
   - ticketbooknetwork
 
  ticketbookingapp:
    container_name: ticket-app
    image: ${DOCKER_REGISTRY-}ticketbookingapp
    build:
      context: .
      dockerfile: TicketBookingApp/Dockerfile
    ports:
        - 8000:8080
    depends_on:
        - ticketdb
        - azurite
        - azurefunction
        - ticketcache

    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ConnectionStrings__DefaultConnection=Server=ticketdb;Database=TicketBooking;User=sa;Password=password@12345#;TrustServerCertificate=True;
        - ConnectionStrings__Redis=ticketcache:6379
        - AzureStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    networks:
     - ticketbooknetwork
 
  ticketcache:
    container_name: ticket-cache
    image: redis:latest
    restart: always
    ports:
    - 6379:6379
    networks:
    - ticketbooknetwork

  azurefunction:
   container_name: azure-function
   build:
    context: .
    dockerfile: AzureFunction/Dockerfile
   depends_on : 
    - ticketdb
    - azurite
    - ticketcache
   environment:
        - ConnectionStrings__DefaultConnection=Server=ticketdb;Database=TicketBooking;User=sa;Password=password@12345#;TrustServerCertificate=True;
        - ConnectionStrings__Redis=ticketcache:6379
        - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        - ASPNETCORE_URLS=http://+:7164
        - AzureStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;     
   ports:
    - 7164:7164
   networks : 
    - ticketbooknetwork

  